hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

# dataSource:
#     pooled: true
#     jmxExport: true
#     driverClassName: org.h2.Driver
#     username: sa
#     password:

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver   
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: root
    password: prospera-1018
environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:mysql://localhost:3306/myapp